### ISSUE TITLE
Voting processor está agindo em todas as mensagens do servidor

### ISSUE THREAD

**Issue by forbidden404** [misterkeebs/clackbot#6]
https://github.com/misterkeebs/clackbot/blob/ea305fa883acb67f75a8135246bd3507d2e72949/src/interfaces/DiscordInterface.js#L31

`Voting` foi criado para ser usado no `banner-pics` e é capaz de evitar que o mesmo usuário dê upvote ou downvote na mesma mensagem, mas esse comportamento não está restrito ao canal de `banner-pics`.

Assim, um usuário não pode reagir com upvote e downvote numa mensagem para replicar o comportamento do clack bot e fazer uma votação manual.

### Comportamento esperado
Reagir fora de um canal de votação deveria permitir que a mesma mensagem tenha upvote e downvote pelo mesmo usuário.

### Comportamento percebido
Ao reagir com upvote e downvote numa mensagem fora de um canal de votação, a última reação toma prioridade.

### Passos para reproduzir o erro

1. Reaja numa mensagem fora de um canal de votação com ⬆.
2. Reaja na mesma mensagem com ⬇.
3. A reação com ⬆ irá sumir, e só restará a reação ⬇.

**Comment by forbidden404** [comment]
Minha proposta seria ter uma constante como VotingChannels, uma lista de todos os canais onde votações ocorrem e o clackbot já reage com upvote e downvote.

Na [linha](https://github.com/misterkeebs/clackbot/blob/ea305fa883acb67f75a8135246bd3507d2e72949/src/processors/Voting.js#L18) que ocorre um early return na função `handleReaction` de `Voting`, poderia se adicionar um condição adicional onde:

`!VotingChannels.includes(reaction.message.channel)`

**Comment by fcoury** [comment]
@forbidden404 excelente ponto, vou adicionar um testcase e resolver esse caso em breve!
